// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiZ0iCv-usUqnQ9bdQB1nC86KktsA76rE',
    appId: '1:555008024586:web:000c12c5df29b79265fff3',
    messagingSenderId: '555008024586',
    projectId: 'fir-auth-19b0e',
    authDomain: 'fir-auth-19b0e.firebaseapp.com',
    storageBucket: 'fir-auth-19b0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYxrNj-nFh1dxZhUPI6Tm1JBPsyRE6vbc',
    appId: '1:555008024586:android:dd1cc65455d6180f65fff3',
    messagingSenderId: '555008024586',
    projectId: 'fir-auth-19b0e',
    storageBucket: 'fir-auth-19b0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCM2WoT4H4t0RPi161eSsnFD3EcpzHpxQ',
    appId: '1:555008024586:ios:585d55ba79783cc565fff3',
    messagingSenderId: '555008024586',
    projectId: 'fir-auth-19b0e',
    storageBucket: 'fir-auth-19b0e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseauth',
  );
}
